export enum PaymentStatus {
  INITIATED = 'INITIATED',
  SUBMITTED = 'SUBMITTED',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  TIMED_OUT = 'TIMED_OUT',
}
